# Generated by Django 2.0.2 on 2018-03-21 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180321_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='workshop',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Horas de taller'),
        ),
    ]
