# Generated by Django 2.0.2 on 2018-03-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180321_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ref_name',
            field=models.CharField(default='not yet', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('1', 'Inboxed'), ('2', 'Waiting'), ('3', 'preparing'), ('4', 'performing'), ('5', 'WorkShop'), ('6', 'Outbox'), ('7', 'Delivered')], default='1', max_length=1),
        ),
    ]
