# Generated by Django 2.0.2 on 2018-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180321_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CIF',
            field=models.CharField(max_length=10, verbose_name='CIF'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(verbose_name='Telefonoa'),
        ),
    ]
