# Generated by Django 2.0.2 on 2018-03-30 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comments',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alta'),
        ),
        migrations.AddField(
            model_name='comments',
            name='reference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
