# Generated by Django 2.0.2 on 2018-03-30 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_auto_20180330_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False, verbose_name='Leido')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Cuando'),
        ),
        migrations.AddField(
            model_name='commentcheck',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Comment'),
        ),
        migrations.AddField(
            model_name='commentcheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
