# Generated by Django 2.0.2 on 2018-05-31 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180419_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=64, verbose_name='Emil'),
        ),
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='chest',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pecho'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Entrega prevista'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hip',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cadera'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inbox_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='lenght',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='others',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepaid',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_name',
            field=models.CharField(max_length=32, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='waist',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cintura'),
        ),
    ]
