# Generated by Django 2.0.2 on 2018-06-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20180608_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='1', max_length=3, verbose_name='Talla'),
        ),
    ]
