# Generated by Django 2.0.2 on 2018-06-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180608_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Leido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Inboxed'), ('2', 'Waiting'), ('3', 'preparing'), ('4', 'performing'), ('5', 'WorkShop'), ('6', 'Outbox'), ('7', 'Delivered'), ('8', 'Cancelled')], default='1', max_length=1),
        ),
    ]
