# Generated by Django 2.0.2 on 2018-06-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180622_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentcheck',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentcheck',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentCheck',
        ),
    ]
