# Generated by Django 2.0.2 on 2018-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180626_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateField(blank=True, verbose_name='Entrega prevista'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.CharField(choices=[('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko')], default='1', max_length=1, verbose_name='Item'),
        ),
    ]
