# Generated by Django 2.0.2 on 2018-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20180629_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='descripcion'),
        ),
    ]
