# Generated by Django 2.0.2 on 2018-09-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
