# Generated by Django 2.0.2 on 2018-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20180914_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='item_class',
            field=models.CharField(choices=[('1', 'Standard'), ('2', 'Medium'), ('3', 'Premium')], default='1', max_length=1, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.CharField(choices=[('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko'), ('9', 'Bata')], default='1', max_length=1, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='item',
            field=models.CharField(choices=[('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko'), ('9', 'Bata')], default='1', max_length=1, verbose_name='Item'),
        ),
    ]
