# Generated by Django 2.0.2 on 2018-09-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20180914_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='reference',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
