# Generated by Django 2.0.2 on 2018-09-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20180919_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='workshop',
        ),
    ]
