# Generated by Django 2.0.2 on 2018-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_remove_order_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.CharField(choices=[('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko'), ('9', 'Bata'), ('10', 'Pololo'), ('11', 'Azpikogona')], default='1', max_length=1, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='item',
            field=models.CharField(choices=[('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko'), ('9', 'Bata'), ('10', 'Pololo'), ('11', 'Azpikogona')], default='1', max_length=1, verbose_name='Item'),
        ),
    ]
