# Generated by Django 2.0.2 on 2018-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20180921_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Inboxed'), ('2', 'Waiting'), ('3', 'Preparing'), ('4', 'Performing'), ('5', 'WorkShop'), ('6', 'Outbox'), ('7', 'Delivered'), ('8', 'Cancelled')], default='1', max_length=1),
        ),
    ]
