# Generated by Django 2.0.2 on 2018-09-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20180927_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.CharField(choices=[('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko'), ('9', 'Bata'), ('10', 'Pololo'), ('11', 'Azpikogona'), ('12', 'Traje de niña')], default='1', max_length=2, verbose_name='Prenda'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='item',
            field=models.CharField(choices=[('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko'), ('9', 'Bata'), ('10', 'Pololo'), ('11', 'Azpikogona'), ('12', 'Traje de niña')], default='1', max_length=2, verbose_name='Prenda'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='item_class',
            field=models.CharField(choices=[('1', 'Standard'), ('2', 'Medium'), ('3', 'Premium')], default='1', max_length=1, verbose_name='Tipo Prenda'),
        ),
    ]
