# Generated by Django 2.0.2 on 2018-10-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20180927_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('1', 'Alta'), ('2', 'Normal'), ('3', 'Baja')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Recibido'), ('2', 'En cola'), ('3', 'Preparando'), ('4', 'En proceso'), ('5', 'Acabado'), ('6', 'En espera'), ('7', 'Entregado'), ('8', 'Cancelado')], default='1', max_length=1),
        ),
    ]
