# Generated by Django 2.0.2 on 2018-10-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20181009_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('1', 'Alta'), ('2', 'Normal'), ('3', 'Baja')], default='2', max_length=1, verbose_name='Prioridad'),
        ),
    ]
