# Generated by Django 2.0.2 on 2018-10-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20181009_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('item_type', models.CharField(choices=[('0', 'No definido'), ('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko'), ('9', 'Bata'), ('10', 'Pololo'), ('11', 'Azpikogona'), ('12', 'Traje de niña')], default=0, max_length=2, verbose_name='Tipo de prenda')),
                ('item_class', models.CharField(choices=[('S', 'Standard'), ('M', 'Medium'), ('P', 'Premium')], default='1', max_length=1, verbose_name='Acabado')),
                ('size', models.CharField(default='1', max_length=3, verbose_name='Talla')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fabrics', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tela (M)')),
            ],
        ),
    ]
