# Generated by Davif on 2018-10-29 21:34

from django.db import migrations, models


def load_item(apps, schema_editor):
    """Add the default item to db."""
    Item = apps.get_model('orders', 'Item')
    Item.objects.create(name='Predeterminado',
                        item_type='0',
                        item_class='0',
                        size=0,
                        fabrics=0)


def delete_item(apps, schema_editor):
    """Roll back the migration."""
    Item = apps.get_model('orders', 'Item')
    Item.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_item'),
    ]

    operations = [
        migrations.RunPython(load_item, delete_item)
    ]
