# Generated by Django 2.0.2 on 2018-11-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_remove_orderitem_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Item'),
        ),
    ]
