# Generated by Django 2.0.2 on 2018-11-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_orderitem_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(default='1', max_length=6, verbose_name='Talla'),
        ),
    ]
