# Generated by Django 2.0.2 on 2018-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_auto_20181114_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foreing',
            field=models.BooleanField(default=False, verbose_name='Externo'),
        ),
    ]
