# Generated by Django 2.0.2 on 2018-11-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_item_foreing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='element',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Item'),
        ),
    ]
