# Generated by Django 2.0.2 on 2018-11-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_orderitem_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('0', 'No definido'), ('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko'), ('9', 'Bata'), ('10', 'Pololo'), ('11', 'Azpikogona'), ('12', 'Traje de niña'), ('13', 'Toquilla')], default=0, max_length=2, verbose_name='Tipo de prenda'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Recibido'), ('2', 'En cola'), ('3', 'Corte'), ('4', 'Confección'), ('5', 'Remate'), ('6', 'En espera'), ('7', 'Entregado'), ('8', 'Cancelado')], default='1', max_length=1),
        ),
    ]
