# Generated by Django 2.0.2 on 2018-12-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_auto_20181201_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
