# Generated by Django 2.0.2 on 2018-12-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_orderitem_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQueue',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.OrderItem')),
                ('score', models.IntegerField(unique=True)),
            ],
        ),
    ]
