# Generated by Django 2.0.2 on 2018-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_auto_20181215_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqueue',
            name='score',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
