# Generated by Django 2.0.2 on 2018-12-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_auto_20181215_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqueue',
            options={'ordering': ['score']},
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio unitario'),
        ),
    ]
