# Generated by Django 2.0.2 on 2018-12-28 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.Order')),
                ('issued_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_no', models.IntegerField(unique=True, verbose_name='Factura no.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Importe con IVA')),
                ('pay_method', models.CharField(choices=[('C', 'Metálico'), ('V', 'Tarjeta'), ('T', 'Transferencia')], default='C', max_length=1, verbose_name='Medio de pago')),
            ],
            options={
                'ordering': ['invoice_no'],
            },
        ),
    ]
