# Generated by Django 2.0.2 on 2019-01-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_no']},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('0', 'No definido'), ('1', 'Falda'), ('2', 'Pantalón'), ('3', 'Camisa'), ('4', 'Pañuelo'), ('5', 'Delantal'), ('6', 'Corpiño'), ('7', 'Chaleco'), ('8', 'Gerriko'), ('9', 'Bata'), ('10', 'Pololo'), ('11', 'Azpikogona'), ('12', 'Traje de niña'), ('13', 'Toquilla'), ('14', 'Bluson'), ('15', 'Kaiku'), ('16', 'Medias'), ('17', 'Bordado')], default='0', max_length=2, verbose_name='Tipo de prenda'),
        ),
    ]
