# Generated by Django 2.0.2 on 2019-01-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_auto_20190104_2139'),
        ('orders', '0060_auto_20190103_0927'),
    ]

    operations = [
    ]
