# Generated by Django 2.0.2 on 2019-01-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_merge_20190105_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepaid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Pagado'),
        ),
    ]
