# Generated by Django 2.0.2 on 2019-01-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_auto_20190105_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prepaid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Prepago'),
        ),
    ]
