# Generated by Django 2.0.2 on 2019-01-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_auto_20190105_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
