# Generated by Django 2.0.2 on 2019-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0065_auto_20190105_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_class',
            field=models.CharField(choices=[('S', 'Standard'), ('M', 'Medium'), ('P', 'Premium')], default='S', max_length=1, verbose_name='Acabado'),
        ),
    ]
