# Generated by Django 2.0.2 on 2019-01-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_auto_20190108_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=32, verbose_name='Localidad'),
        ),
    ]
