# Generated by Django 2.0.2 on 2019-01-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_auto_20190115_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='element',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Item'),
        ),
    ]
