# Generated by Django 2.0.2 on 2019-01-18 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_auto_20190115_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alta')),
                ('invoice_no', models.CharField(max_length=64, verbose_name='Número de factura')),
                ('issued_on', models.DateField(verbose_name='Emisión')),
                ('concept', models.CharField(max_length=64, verbose_name='Concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Importe con IVA')),
                ('pay_method', models.CharField(choices=[('C', 'Metálico'), ('V', 'Tarjeta'), ('T', 'Transferencia')], default='T', max_length=1, verbose_name='Medio de pago')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='provider',
            field=models.BooleanField(default=False, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='expense',
            name='issuer',
            field=models.ForeignKey(limit_choices_to={'provider': True}, on_delete=django.db.models.deletion.PROTECT, to='orders.Customer'),
        ),
    ]
