# Generated by Django 2.0.2 on 2019-01-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0072_expense_in_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CIF',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIF'),
        ),
    ]
