# Generated by Django 2.0.2 on 2019-03-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0073_auto_20190123_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',)},
        ),
    ]
