# Generated by Django 2.0.2 on 2019-03-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_auto_20190309_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='Confirmado'),
        ),
    ]
