# Generated by Django 2.2 on 2019-05-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_timetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ('start',)},
        ),
    ]
