# Generated by Django 2.2 on 2019-12-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0077_auto_20190527_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.BooleanField(default=False, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='order',
            name='membership',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_order', to='orders.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Customer'),
        ),
    ]
