# Generated by Django 2.2 on 2019-12-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0079_cashflowio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflowio',
            options={'ordering': ['-creation']},
        ),
        migrations.AddField(
            model_name='expense',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
        migrations.AlterField(
            model_name='cashflowio',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfio_prepaids', to='orders.Order'),
        ),
    ]
