# Generated by Django 2.2 on 2019-12-16 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0080_auto_20191215_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowio',
            name='expense',
            field=models.ForeignKey(blank=True, limit_choices_to={'closed': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Expense'),
        ),
        migrations.CreateModel(
            name='StatusShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Recibido'), ('2', 'En cola'), ('3', 'Corte'), ('4', 'Confección'), ('5', 'Remate'), ('6', 'En espera'), ('7', 'Entregado'), ('8', 'Cancelado')], default='1', max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_shift', to='orders.Order')),
            ],
        ),
    ]
