# Generated by Django 2.2 on 2019-12-21 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0081_statusshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='consultancy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Icebox'), ('2', 'En cola'), ('3', 'En proceso'), ('4', 'Confección'), ('5', 'Remate'), ('6', 'En espera'), ('7', 'Entregado'), ('8', 'Cancelado'), ('9', 'Facturado')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='element',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='statusshift',
            name='status',
            field=models.CharField(choices=[('1', 'Icebox'), ('2', 'En cola'), ('3', 'En proceso'), ('4', 'Confección'), ('5', 'Remate'), ('6', 'En espera'), ('7', 'Entregado'), ('8', 'Cancelado'), ('9', 'Facturado')], default='1', max_length=1),
        ),
    ]
