# Generated by Django 2.2 on 2019-12-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0084_auto_20191221_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(customer__name__iexact='trapuzarrak'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='orders.Order'),
        ),
    ]
