# Generated by Django 2.2 on 2019-12-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0086_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='health',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='stocked',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Stock uds'),
        ),
    ]
