# Generated by Django 2.2 on 2020-01-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0087_auto_20191228_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_sales',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='year_sales',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
    ]
