# Generated by Django 2.2 on 2020-01-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0088_auto_20200106_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowio',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='closed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Cerrado'),
        ),
    ]
